travis:
  secure:
    BINSTAR_TOKEN: Kmso+7pFk2ZnD2y+ccdHM10RjMvKXrKtZV8QDS6+CX/cXBBEO0pr95U3qWUaAR/3j3cU/UrItQ+O1Q+j1zmDPQecX4nnrTUo2ocBBJoqOWjWIVav4lyxyrfzuRYUOisUbQQwVp4Tnv3+FXCAcOd9OnoSqIfjwR2ZAOiohRgdip0y/7Mh3q1dHP8yCNVIrW6fwWfgwVzlS+enMe3s/Zu+VHi3QTLCkKv191afHVtGqt6/4ZlhIXtbPHbwMUMyobXbMbbXWi4KBXHH48TJxp1crOJ2p4fNN0tpwAJsaZTNXSTxLGn1dhIYnla1CCA0/6XGyZXRKSTEOO5pxBcYGWPUdnfHc0pWfNN/4Sm75p5agLdx5HJhiTY95n02QdAVrGRdTc9EOC+UD7HGeoftxwwLUAWKF7OYeOjM+sxPSWIxhaTn9/4hBqgTNJmgPufPbEFFbSpGImGFZWIrArlWKSTm9wlvZpdbXsoEAtvetd3E1XoAr1X1I+GYZ1XEaR3/wvl+9SS4QLTvxCUOnetcnRXBFxH00C4KRbpUn//QJU9WUL1TsGUYWh/N5j2cL9KWKY109MrtJajLabPpxNo1luVwrmAypSjDnUov8wlkUDehS0RkQ8rRI0mnc8BGmQSPv6nqI5/JzztpWbtnTU+7oZkjM4BW6vuQU3TNDj8cudb2pkY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
